name: Amxmodx Builder Master Workflow
on:
  push:
    branches:
      - master
    paths:
      - amxmodx-builder/**
jobs:
  main:
    name: Build and push docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.8.2"
            build_url: "https://www.amxmodx.org/release/amxmodx-1.8.2-base-linux.tar.gz"
          - version: "1.8.3"
            build_url: "https://www.amxmodx.org/amxxdrop/1.8/amxmodx-1.8.3-dev-git5201-base-linux.tar.gz"
          - version: "1.9.0"
            build_url: "https://www.amxmodx.org/amxxdrop/1.9/amxmodx-1.9.0-git5241-base-linux.tar.gz"
          - version: "1.10.0"
            build_url: "https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5392-base-linux.tar.gz"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./amxmodx-builder
          push: true
          tags: budziam/amxmodx-builder:${{ matrix.version }}
          build-args: |
            BUILD_URL=${{ matrix.build_url }}
