name: Sourcemod Builder Pull Request Workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - sourcemod-builder/**
jobs:
  main:
    name: Build docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "1.10.0"
          - version: "1.11.0"
          - version: "1.12.0"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Get commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./sourcemod-builder
          push: true
          tags: budziam/sourcemod-builder:${{ matrix.version }}-${{ steps.vars.outputs.sha_short }}
          build-args: |
            BUILD_VERSION=${{ matrix.version }}
